spring:
  application:
    name: registry-ms

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost
  wait-time-in-ms-when-sync-empty: 0

---
spring:
  application:
    name: registry-ms
  profiles:
    active: docker

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://registry-ms:8080/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: registry-ms
  wait-time-in-ms-when-sync-empty: 0